### PR TITLE
Refresh scaleway sdk

### PR DESCRIPTION
**Pull request by lion24**
Hi Isaac,

First of all, thanks for this amazing SDK, the way it is built / coded makes it so easy to extend and is really easy to understand, well done!

I just tried to use this java scaleway sdk with the jenkins cloud plugin. I have a personal project and it would be amazing to spawn jenkins slave on demand on Scaleway, just because I love them :) But the SDK reports some errors due to API changes.

Indeed, the guys at scaleway changed a lot their API, I took the liberty to refresh this SDK to match their new API structure :) Now, the creation + deletion of an instance work out of the box.
This is still work in progress and I'm planning to also add cloud-init support via the API. If this is OK for you we can maybe already merge this part.

I'm not a Java specialist so don't blame my coding mistake :sweat_smile:

Best regards,
Lionel.

### CODE REVIEW

**Review by segator — APPROVED** [review]
Amazing lets integrate on master and release a new version on maven-central!

**Comment by lion24** [comment]
Amazing! I was not expected to be merged at first time!

Was my pleasure to make this pull request :-)
As I said, I'm also planning to add cloud-init support, so expect a PR in coming weeks ;-)


Best regards,
Lionel.

**Comment by segator** [comment]
your PR was okey compared the other code and I did some tests and works.
What could we nice is to add some unit test to the code.
and happy to review coming PR's 👍

**Comment by lion24** [comment]
> What could we nice is to add some unit test to the code.

Yes definitely, unit tests would be a nice to have.

Have a nice day.

**Pull request merged**
